# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3cda80d32738370c002ec054947a96e1913e2056f62c6a304978c29cf1aa4b796eb40604679175799ba3587a69e0d3e7cf67f602b3b9dfd8f8d609cf7aea66b5

test:
  secret_key_base: 3ea4ffbd745d796401ad8662b0c6f9be8f09078f351fbda0bf55a3ffc03068e72004057dd822030951fdb12d2b22257fbad3b09b8fa67dc2ecebfc9aef9005fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
